package com.example.backend.enums;

public enum EnergyCalculationType {
  ERZEUGTE_ENERGIE,
  GENUTZTE_ENERGIE,
  WIRKLEISTUNG,
  BLINDLEISTUNG_REACTIVPOWER,
  SCHEINLEISTUNG_RESERVED,
  SPANNUNG_L1_VOLTS,
  SPANNUNG_L2_VOLTS,
  SPANNUNG_L3_VOLTS,
  FREQUENZ,
  STROM
}
