package com.example.backend.enums;

public enum HeatingCalculationType {
  ERZEUGTE_ENERGIE_HEATING,
  VORLAUFTEMPERATUR,
  VOLUMENSTROM,
  TEMPERATURDIFFERENZ,
  LEISTUNG,
  GESAMT_VOLUMEN,
  RuCKLAUFTEMPERATUR

}
