export const EnergyCalculationType = {
    ERZEUGTE_ENERGIE: 'ERZEUGTE_ENERGIE',
    GENUTZTE_ENERGIE: 'GENUTZTE_ENERGIE',
    WIRKLEISTUNG: 'WIRKLEISTUNG',
    BLINDLEISTUNG_REACTIVPOWER: 'BLINDLEISTUNG_REACTIVPOWER',
    SCHEINLEISTUNG_RESERVED: 'SCHEINLEISTUNG_RESERVED',
    SPANNUNG_L1_VOLTS: 'SPANNUNG_L1_VOLTS',
    SPANNUNG_L2_VOLTS: 'SPANNUNG_L2_VOLTS',
    SPANNUNG_L3_VOLTS: 'SPANNUNG_L3_VOLTS',
    FREQUENZ: 'FREQUENZ',
    STROM: 'STROM',
    };
    
    export const HeatingCalculationTypes = {
      ERZEUGTE_ENERGIE_HEATING:'ERZEUGTE_ENERGIE_HEATING',
      VORLAUFTEMPERATUR:'VORLAUFTEMPERATUR',
      VOLUMENSTROM:'VOLUMENSTROM',
      TEMPERATURDIFFERENZ:'TEMPERATURDIFFERENZ',
      LEISTUNG:'LEISTUNG',
      GESAMT_VOLUMEN:'GESAMT_VOLUMEN',
      RuCKLAUFTEMPERATUR:'RuCKLAUFTEMPERATUR',
  
    };
  
  