export const EnergyCalculationType = {
  GENERATED_ENERGY: 'GENERATED_ENERGY',
  CONSUMED_ENERGY: 'CONSUMED_ENERGY',
  ACTIVE_POWER: 'ACTIVE_POWER',
  REACTIVE_POWER_BLIND_POWER: 'REACTIVE_POWER_BLIND_POWER',
  APPARENT_POWER_RESERVED: 'APPARENT_POWER_RESERVED',
  VOLTAGE_L1_VOLTS: 'VOLTAGE_L1_VOLTS',
  VOLTAGE_L2_VOLTS: 'VOLTAGE_L2_VOLTS',
  VOLTAGE_L3_VOLTS: 'VOLTAGE_L3_VOLTS',
  FREQUENCY: 'FREQUENCY',
  CURRENT: 'CURRENT',
  COS_PHI: 'COS_PHI',
};

export const HeatingCalculationTypes = {
  GENERATED_ENERGY_HEATING: 'GENERATED_ENERGY_HEATING',
  SUPPLY_TEMPERATURE: 'SUPPLY_TEMPERATURE',
  RETURN_TEMPERATURE: 'RETURN_TEMPERATURE',
  TEMPERATURE_DIFFERENCE: 'TEMPERATURE_DIFFERENCE',
  VOLUME_FLOW: 'VOLUME_FLOW',
  POWER: 'POWER',
  TOTAL_VOLUME: 'TOTAL_VOLUME',
};

export const GasTypes = {
  GAS_TEMPERATURE: 'GAS_TEMPERATURE',
  GAS_PRESSURE: 'GAS_PRESSURE',
  GAS_METER: 'GAS_METER',
  AMBIENT_TEMPERATURE: 'AMBIENT_TEMPERATURE',
  AMBIENT_PRESSURE: 'AMBIENT_PRESSURE',
  GAS_POWER: 'GAS_POWER',
  ELECTRICAL_EFFICIENCY: 'ELECTRICAL_EFFICIENCY',
  THERMAL_EFFICIENCY: 'THERMAL_EFFICIENCY',
  OVERALL_EFFICIENCY: 'OVERALL_EFFICIENCY',

};

export const ChpCalculationType = { //BhkwTypes
  HEATING_WATER_RETURN: 'HEATING_WATER_RETURN',
  HEATING_WATER_FLOW: 'HEATING_WATER_FLOW',
  ENGINE_COOLANT_RETURN: 'ENGINE_COOLANT_RETURN',
  ENGINE_COOLANT_FLOW: 'ENGINE_COOLANT_FLOW',
  CONTROL_CABINET: 'CONTROL_CABINET',
  HOUSING: 'HOUSING',
  EXHAUST_TEMPERATURE: 'EXHAUST_TEMPERATURE',
  GENERATOR_WINDING: 'GENERATOR_WINDING',
  ENGINE_OIL: 'ENGINE_OIL',
  ENGINE_COOLANT: 'ENGINE_COOLANT',
  OPERATING_HOURS: 'OPERATING_HOURS',
  START_COUNT: 'START_COUNT',


};

export const unitMapping = {
  GENERATED_ENERGY: 'kWh',
  CONSUMED_ENERGY: 'kWh',
  ACTIVE_POWER: 'W',
  REACTIVE_POWER_BLIND_POWER: 'kVAR',
  APPARENT_POWER_RESERVED: 'Res',
  VOLTAGE_L1_VOLTS: 'V',
  VOLTAGE_L2_VOLTS: 'V',
  VOLTAGE_L3_VOLTS: 'V',
  FREQUENCY: 'Hz',
  CURRENT: 'A',
  GENERATED_ENERGY_HEATING: 'kWh',
  SUPPLY_TEMPERATURE: '°C',
  VOLUME_FLOW: 'l/min',
  TEMPERATURE_DIFFERENCE: '°C',
  POWER: 'kW',
  TOTAL_VOLUME: 'm³',
  RETURN_TEMPERATURE: '°C',
  GAS_TEMPERATURE: '°C',
  GAS_PRESSURE: 'mbar',
  GAS_METER: 'm³',
  AMBIENT_TEMPERATURE: '°C',
  AMBIENT_PRESSURE: 'mbar',
  EXHAUST_TEMPERATURE: '°C',
  HEATING_WATER_FLOW: '°C',
  HEATING_WATER_RETURN: '°C',
  ENGINE_COOLANT_FLOW: '°C',
  ENGINE_COOLANT_RETURN: '°C',
  CONTROL_CABINET: '°C',
  HOUSING: '°C',
  GENERATOR_WINDING: '°C',
  ENGINE_OIL: '°C',
  GAS_POWER: 'kWh',
  ELECTRICAL_EFFICIENCY: '%',
  THERMAL_EFFICIENCY: '%',
  OVERALL_EFFICIENCY: '%',
  OPERATING_HOURS: 'Stunden',
  START_COUNT: '',
  ENGINE_COOLANT: '°C',
  COS_PHI: '',

};

export const displayNameMapping = {
  GENERATED_ENERGY: 'ERZEUGTE ENERGIE',
  CONSUMED_ENERGY: 'GENUTZTE ENERGIE',
  ACTIVE_POWER: 'WIRKLEISTUNG ',
  REACTIVE_POWER_BLIND_POWER: 'BLINDLEISTUNG',
  APPARENT_POWER_RESERVED: 'SCHEINLEISTUNG',
  VOLTAGE_L1_VOLTS: 'SPANNUNG L1 VOLTS',
  VOLTAGE_L2_VOLTS: 'SPANNUNG L2 VOLTS',
  VOLTAGE_L3_VOLTS: 'SPANNUNG L3 VOLTS',
  FREQUENCY: 'FREQUENZ',
  CURRENT: 'STROM',
  COS_PHI: 'COS PHI',


  GENERATED_ENERGY_HEATING: 'ERZEUGTE ENERGIE',
  SUPPLY_TEMPERATURE: 'VORLAUFTEMPERATUR',
  RETURN_TEMPERATURE: 'RÜCKLAUFTEMPERATUR',
  TEMPERATURE_DIFFERENCE: 'TEMPERATURDIFFERENZ',
  VOLUME_FLOW: 'VOLUMENSTROM',
  POWER: 'LEISTUNG',
  TOTAL_VOLUME: 'GESAMTVOLUMEN',


  HEATING_WATER_RETURN: 'HEIZUNGSWASSER-RÜCKLAUF (T01)',
  HEATING_WATER_FLOW: 'HEIZUNGSWASSER-VORLAUF (T02)',
  ENGINE_COOLANT_RETURN: 'MOTORKÜHLMITTEL-RÜCKLAUF (T03)',
  ENGINE_COOLANT_FLOW: 'MOTORKÜHLMITTEL-VORLAUF (T04)',
  CONTROL_CABINET: 'SCHALTSCHRANK (T05)',
  HOUSING: 'GEHÄUSE (T06)',
  EXHAUST_TEMPERATURE: 'ABGASTEMPERATUR (T07)',
  GENERATOR_WINDING: 'GENERATORWICKLUNG (T08)',
  ENGINE_OIL: 'MOTORÖL (T09)',
  ENGINE_COOLANT: 'MOTORKÜHLMITTEL (T10) ASV30 / ASV40',
  OPERATING_HOURS: 'BETRIEBSSTUNDEN',
  START_COUNT: 'STARTANZAHL',


  GAS_TEMPERATURE: 'GASTEMPERATUR',
  GAS_PRESSURE: 'GASDRUCK',
  GAS_METER: 'GASZÄHLER',
  AMBIENT_TEMPERATURE: 'UMGEBUNGSTEMPERATUR',
  AMBIENT_PRESSURE: 'UMGEBUNGSDRUCK',

  GAS_POWER: 'GASLEISTUNG',
  ELECTRICAL_EFFICIENCY: 'ELEKTRISCHER WIRKUNGSGRAD',
  THERMAL_EFFICIENCY: 'THERMISCHER WIRKUNGSGRAD',
  OVERALL_EFFICIENCY: 'GESAMTWIRKUNGSGRAD'
};

